package.json
src/components/PageFooter/CommunityLink.tsx
src/components/PageFooter/PageFooter.tsx
src/components/index.tsx
src/index.tsx

<details>
<summary>📦 Published PR as canary version: <code>0.1.1-canary.1.1b15385.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@0.1.1-canary.1.1b15385.0
yarn add @storybook/components-marketing@0.1.1-canary.1.1b15385.0
```
</details>

update chromatic link

---

src/components/IllustratedFeatureList.tsx
src/components/SectionLede.tsx
src/components/Testimonial.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.2--canary.17.c82ddb2.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.2--canary.17.c82ddb2.0
yarn add @storybook/components-marketing@2.0.2--canary.17.c82ddb2.0
```
</details>

tweaks to illustrated list, section lede and testimonial components

---

src/components/IntegrationsCarousel.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.5--canary.20.43422f9.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.5--canary.20.43422f9.0
yarn add @storybook/components-marketing@2.0.5--canary.20.43422f9.0
```
</details>

fix height

---

src/components/CollapsedNav.tsx
src/components/IconButton.tsx
src/components/IntegrationsCarousel.tsx
src/components/Nav/MobileMenu.tsx
src/components/Nav/Nav.stories.tsx
src/components/Nav/Nav.tsx
src/components/Nav/NavItem.tsx
src/components/Nav/TabletMenu.tsx
src/components/Nav/index.ts
src/components/Nav/menus.tsx
src/components/NavMenu/NavMenu.tsx
src/components/NavMenu/NavMenuButton.tsx
src/components/Search.stories.tsx
src/components/Search.tsx
src/components/SectionLede.tsx
src/components/ValuePropCopy.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.9--canary.23.2a3e533.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.9--canary.23.2a3e533.0
yarn add @storybook/components-marketing@2.0.9--canary.23.2a3e533.0
```
</details>

Nav updates

---

src/components/Eyebrow.tsx
src/components/Nav/Nav.stories.tsx
src/components/Nav/Nav.tsx
src/components/SubNav/SubNav.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.12--canary.26.8110be6.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.12--canary.26.8110be6.0
yarn add @storybook/components-marketing@2.0.12--canary.26.8110be6.0
```
</details>

Fix nav borders

---

src/components/IllustratedFeatureList.tsx
src/components/NormalizeArea.stories.tsx
src/components/NormalizeArea.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.13--canary.27.5a31ed7.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.13--canary.27.5a31ed7.0
yarn add @storybook/components-marketing@2.0.13--canary.27.5a31ed7.0
```
</details>

Misc updates

---

src/components/Footer/Footer.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.15--canary.29.875b4a0.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.15--canary.29.875b4a0.0
yarn add @storybook/components-marketing@2.0.15--canary.29.875b4a0.0
```
</details>

fix twitter link in footer

---

src/components/LocalSearch.stories.tsx
src/components/LocalSearch.tsx
src/components/StackedNav.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.18--canary.32.1cb8a23.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.18--canary.32.1cb8a23.0
yarn add @storybook/components-marketing@2.0.18--canary.32.1cb8a23.0
```
</details>

Local search

---

src/components/IllustratedFeatureList.tsx
src/components/IntegrationsCarousel.stories.tsx
src/components/IntegrationsCarousel.tsx
src/components/Nav/NavItem.stories.tsx
src/components/Nav/NavItem.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.23--canary.37.4e8d45c.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.23--canary.37.4e8d45c.0
yarn add @storybook/components-marketing@2.0.23--canary.37.4e8d45c.0
```
</details>

IntegrationsCarousel remove auto animation

---

src/components/links-context.ts

<details>
<summary>📦 Published PR as canary version: <code>2.0.27--canary.41.7e3d257.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.27--canary.41.7e3d257.0
yarn add @storybook/components-marketing@2.0.27--canary.41.7e3d257.0
```
</details>

Update `whyStorybook` URL

---

src/components/Nav/MobileMenu.stories.tsx
src/components/Nav/MobileMenu.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.31--canary.45.4e6bb77.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.31--canary.45.4e6bb77.0
yarn add @storybook/components-marketing@2.0.31--canary.45.4e6bb77.0
```
</details>

close mobile menu on click

---

src/components/Drawer.tsx
src/components/SubNav/SubNavTabs.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.32--canary.46.b9433e6.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.32--canary.46.b9433e6.0
yarn add @storybook/components-marketing@2.0.32--canary.46.b9433e6.0
```
</details>

Drawer fix

---

src/components/NotFoundScreen/NotFoundScreen.tsx
src/components/SearchBlock.stories.tsx
src/components/SearchBlock.tsx
src/components/SupportFeature.stories.tsx
src/components/SupportFeature.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.33--canary.47.63772a4.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.33--canary.47.63772a4.0
yarn add @storybook/components-marketing@2.0.33--canary.47.63772a4.0
```
</details>

SupportFeature and SearchBlock

---

src/components/NotFoundScreen/NotFoundScreen.tsx
src/components/SupportFeature.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.35--canary.49.ee90916.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.35--canary.49.ee90916.0
yarn add @storybook/components-marketing@2.0.35--canary.49.ee90916.0
```
</details>

remove max width from SupportFeatureGrid

---

src/components/Nav/Nav.stories.tsx
src/components/Nav/Nav.tsx
src/components/Nav/menus.tsx
src/components/NavMenu/NavMenu.tsx
src/components/NavMenu/NavMenuButton.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.36--canary.50.aad0359.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.36--canary.50.aad0359.0
yarn add @storybook/components-marketing@2.0.36--canary.50.aad0359.0
```
</details>

add active state to nav

---

package.json
src/components/SocialCard.tsx
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>2.0.38--canary.52.0b9f9f1.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.38--canary.52.0b9f9f1.0
yarn add @storybook/components-marketing@2.0.38--canary.52.0b9f9f1.0
```
</details>

adjust social card styling on mobile

---

src/components/Eyebrow.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.39--canary.53.6553442.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.39--canary.53.6553442.0
yarn add @storybook/components-marketing@2.0.39--canary.53.6553442.0
```
</details>

fix eyebrow link styling

---

src/components/Footer/Footer.stories.tsx
src/components/Footer/Footer.tsx
src/components/links-context.ts

<details>
<summary>📦 Published PR as canary version: <code>2.0.42--canary.58.4b0e248.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.42--canary.58.4b0e248.0
yarn add @storybook/components-marketing@2.0.42--canary.58.4b0e248.0
```
</details>

Add `/status` link to Footer

---

src/components/Eyebrow.tsx
src/components/Nav/Nav.stories.tsx
src/components/Nav/Nav.tsx
src/components/Nav/menus.tsx
src/components/links-context.ts

<details>
<summary>📦 Published PR as canary version: <code>2.1.1--canary.67.79de9dd.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.1.1--canary.67.79de9dd.0
yarn add @storybook/components-marketing@2.1.1--canary.67.79de9dd.0
```
</details>

Add enterprise link in nav

---

src/components/Footer/Footer.stories.tsx
src/components/Footer/Footer.tsx
src/components/Nav/Nav.stories.tsx
src/components/Nav/menus.tsx
src/components/links-context.ts

Added two links to header + footer for Joe.

Add conference and jobs board to header and footer

---

src/components/Nav/MobileMenu.stories.tsx
src/components/Nav/MobileMenu.tsx
src/components/Nav/Nav.stories.tsx
src/components/Nav/Nav.tsx
src/components/Nav/menus.tsx
src/components/Search.stories.tsx
src/components/Search.tsx
src/components/SearchBlock.tsx
src/components/SubNav/SubNav.stories.tsx

_Only created a PR to generate an alpha release to reference in linked PR._
- See: https://github.com/storybookjs/frontpage/pull/626
<details>
<summary>📦 Published PR as canary version: <code>2.1.5--canary.71.0d954ff.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.1.5--canary.71.0d954ff.0
yarn add @storybook/components-marketing@2.1.5--canary.71.0d954ff.0
```
</details>

DO NOT MERGE: Updates for new docs design

---

package.json
src/components/Footer/Footer.tsx
src/components/MailingList/MailingListSignup.tsx
yarn.lock

- Fix footer button
- Replace Twitter icon in the footer
> **NOTE**
> This release is marked as `major` to account for breaking changes that accidentally shipped in [2.3.1](https://github.com/storybookjs/components-marketing/releases/tag/v2.3.1)
<details>
<summary>📦 Published PR as canary version: <code>3.0.0--canary.77.1cb3594.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@3.0.0--canary.77.1cb3594.0
yarn add @storybook/components-marketing@3.0.0--canary.77.1cb3594.0
```
</details>

Small fixes after Storybook 8 launch

---

src/components/Footer/Footer.tsx
src/components/Nav/Nav.tsx
src/components/Nav/menus.tsx

<details>
<summary>📦 Published PR as canary version: <code>3.1.0--canary.80.9ddb05f.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@3.1.0--canary.80.9ddb05f.0
yarn add @storybook/components-marketing@3.1.0--canary.80.9ddb05f.0
```
</details>

Add Addons (Integrations) nav item
