src/components/SectionLede.tsx

Minor max-width change
<details>
<summary>📦 Published PR as canary version: <code>0.1.1-canary.9.08a038d.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@0.1.1-canary.9.08a038d.0
yarn add @storybook/components-marketing@0.1.1-canary.9.08a038d.0
```
</details>

SectionLede: Forgot to add this max-width

---

.storybook/preview.js
README.md
package.json
src/components/CollapsedNav.tsx
src/components/Menu/Menu.tsx
src/components/NavMenu/NavMenu.tsx
src/components/Search.tsx
yarn.lock

- Downgrade `react-merge-refs` to `^1.10`
- `^2.0.0` is ESM-only (https://github.com/gregberge/react-merge-refs/releases/tag/v2.0.0), making integration in various projects (namely Next.js) difficult at the moment
- This may cause issues in environments like jest: https://github.com/gregberge/react-merge-refs/issues/16
- Currently not an issue, as there are no tests
- Remove `@docsearch/css` import from Search
- Next.js requires all global CSS to be imported in the top-level App component
- Move it from deps to peerDeps
- Add instructions to README
<details>
<summary>📦 Published PR as canary version: <code>2.0.8--canary.22.778d242.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.8--canary.22.778d242.0
yarn add …
```

[Do not merge] Fixes for integration

---

src/components/Nav/MobileMenu.tsx
src/components/Nav/Nav.tsx
src/components/Search.tsx

- Passing a number means `7.0` is condensed to `7`, when Algolia expects "7.0"
<details>
<summary>📦 Published PR as canary version: <code>2.0.10--canary.24.de4d51f.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.10--canary.24.de4d51f.0
yarn add @storybook/components-marketing@2.0.10--canary.24.de4d51f.0
```
</details>

Fix type of `version` prop for Search

---

src/components/Eyebrow.stories.tsx
src/components/Eyebrow.tsx
src/components/Footer/Footer.stories.tsx
src/components/Footer/Footer.styles.ts
src/components/Footer/Footer.tsx
src/components/GithubButton.stories.tsx
src/components/GithubButton.tsx
src/components/IntegrationsCarousel.stories.tsx
src/components/LinkWithWrapper.tsx
src/components/Nav/Nav.stories.tsx
src/components/links-context.ts

<details>
<summary>📦 Published PR as canary version: <code>2.0.14--canary.28.ae4b3d7.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.14--canary.28.ae4b3d7.0
yarn add @storybook/components-marketing@2.0.14--canary.28.ae4b3d7.0
```
</details>

fix LinkWithWrapper and fetch github stars from dx-data fn

---

src/components/SubNav/SubNav.stories.tsx
src/components/SubNav/SubNavLinkList.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.1.0--canary.35.23d8099.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.1.0--canary.35.23d8099.0
yarn add @storybook/components-marketing@2.1.0--canary.35.23d8099.0
```
</details>

Add `inverse` support to SubNavLinkList

---

src/components/NotFoundScreen/PuzzlePieces.tsx
src/components/SubNav/SubNavLinkList.tsx

- Fix color of SubNavLinkList label when `inverse={true}`
- Add `data-chromatic="ignore"` to PuzzlePieces, as the animation is non-deterministic
<details>
<summary>📦 Published PR as canary version: <code>2.0.22--canary.36.c67ba3d.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.22--canary.36.c67ba3d.0
yarn add @storybook/components-marketing@2.0.22--canary.36.c67ba3d.0
```
</details>

Fix visual bugs

---

src/components/FeatureStep.tsx
src/components/Testimonial.tsx

Minor cosmetic change that came out of site QA
<details>
<summary>📦 Published PR as canary version: <code>2.0.28--canary.42.38f833e.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.28--canary.42.38f833e.0
yarn add @storybook/components-marketing@2.0.28--canary.42.38f833e.0
```
</details>

Shrink the Testimonial quote on mobile

---

src/components/SocialCard.tsx

Bumps up spacing by 4px 
<details>
<summary>📦 Published PR as canary version: <code>2.0.29--canary.43.7e3b321.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.29--canary.43.7e3b321.0
yarn add @storybook/components-marketing@2.0.29--canary.43.7e3b321.0
```
</details>

Visual tweak of social card button + cardinal spacing

---

src/components/IllustratedFeatureList.tsx

Fixes autoplay for Document and Test videos
@winkerVSbecks can you review and update the package in the frontpage?
<details>
<summary>📦 Published PR as canary version: <code>2.0.40--canary.54.89c863a.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.40--canary.54.89c863a.0
yarn add @storybook/components-marketing@2.0.40--canary.54.89c863a.0
```
</details>

Fix autoplay for videos

---

src/components/links-context.ts

Update the default link for integrations in the footer
<details>
<summary>📦 Published PR as canary version: <code>2.0.41--canary.55.2979e5e.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.41--canary.55.2979e5e.0
yarn add @storybook/components-marketing@2.0.41--canary.55.2979e5e.0
```
</details>

Update default links

---

src/components/Search.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.43--canary.59.e71de9c.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.43--canary.59.e71de9c.0
yarn add @storybook/components-marketing@2.0.43--canary.59.e71de9c.0
```
</details>

Add recipe values for doc search facets

---

src/components/links-context.ts

Because of https://github.com/storybookjs/storybook/pull/21393
DO NOT MERGE until after:
1. https://github.com/storybookjs/storybook/pull/21393
2. https://github.com/storybookjs/frontpage/pull/494
After merging, ensure various SB sub-sites are rebuilt with newest version of this package
<details>
<summary>📦 Published PR as canary version: <code>2.0.45--canary.61.049d63f.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.45--canary.61.049d63f.0
yarn add @storybook/components-marketing@2.0.45--canary.61.049d63f.0
```
</details>

Update `whyStorybook` URL

---

src/components/Menu/Menu.tsx
src/components/NavMenu/NavMenu.tsx

- NavMenuPanel now composes MenuPanel
- Mostly so that it receive's MenuPanel's `z-index` value
<details>
<summary>📦 Published PR as canary version: <code>2.0.45--canary.62.61a6d98.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.45--canary.62.61a6d98.0
yarn add @storybook/components-marketing@2.0.45--canary.62.61a6d98.0
```
</details>

Fix NavMenu styles

---

src/components/Drawer.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.47--canary.65.168c43c.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.47--canary.65.168c43c.0
yarn add @storybook/components-marketing@2.0.47--canary.65.168c43c.0
```
</details>

reduce z-index for drawer to show search on mobile

---

src/components/Eyebrow.tsx

- Remove Storybook Day badge
- Change “automate with Chromatic” to “Visual test with Chromatic”
<details>
<summary>📦 Published PR as canary version: <code>2.0.48--canary.66.bd88fc6.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.0.48--canary.66.bd88fc6.0
yarn add @storybook/components-marketing@2.0.48--canary.66.bd88fc6.0
```
</details>

Tweak header, remove SB Day

---

src/components/CollapsedNav.tsx

On the docs, the main navigation is fixed. To make sure the nav mobile is always on top, we need to add a `z-index` to it.
<details>
<summary>📦 Published PR as canary version: <code>2.1.4--canary.72.a7751f0.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.1.4--canary.72.a7751f0.0
yarn add @storybook/components-marketing@2.1.4--canary.72.a7751f0.0
```
</details>

Add z-index to mobile nav to make sure it always sit on top.

---

src/components/Footer/Footer.stories.tsx
src/components/Footer/Footer.tsx
src/components/Nav/Nav.stories.tsx
src/components/Nav/menus.tsx
src/components/links-context.ts

We're discontinuing these initiatives as Joe is focusing on other things.
heads up @winkerVSbecks we'll have to update the package in sb/frontpage for this to take effect
<details>
<summary>📦 Published PR as canary version: <code>2.2.1--canary.73.d78807a.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.2.1--canary.73.d78807a.0
yarn add @storybook/components-marketing@2.2.1--canary.73.d78807a.0
```
</details>

Remove jobs board and conferences board from Header and Footer

---

package.json
src/components/Eyebrow.tsx
src/components/Footer/Services.tsx
src/components/links-context.ts
yarn.lock

- Use new `/storybook` route
<details>
<summary>📦 Published PR as canary version: <code>2.3.0--canary.75.92a8709.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.3.0--canary.75.92a8709.0
yarn add @storybook/components-marketing@2.3.0--canary.75.92a8709.0
```
</details>

Update Chromatic links

---

package.json
src/components/Eyebrow.tsx
src/components/Footer/Footer.styles.ts
src/components/GithubButton.tsx
src/components/IllustratedFeatureList.tsx
src/components/Nav/Nav.stories.tsx
src/components/Nav/Nav.tsx
src/components/Nav/NavItem.tsx
yarn.lock

We updated Storybook's homepage to use a new design that require some changes on the main nav and footer mostly.
<details>
<summary>📦 Published PR as canary version: <code>2.3.1--canary.74.9140eb1.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.3.1--canary.74.9140eb1.0
yarn add @storybook/components-marketing@2.3.1--canary.74.9140eb1.0
```
</details>

Fix global navigation for the new homepage for SB8

---

src/components/GithubButton.tsx

In this PR we are changing the link to Github to point directly to the core repo instead of the list of stargazers.
<details>
<summary>📦 Published PR as canary version: <code>2.3.2--canary.76.fa52690.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@2.3.2--canary.76.fa52690.0
yarn add @storybook/components-marketing@2.3.2--canary.76.fa52690.0
```
</details>

Update Github button link

---

src/components/Footer/Footer.stories.tsx
src/components/Footer/Footer.tsx
src/components/links-context.ts

See also: https://github.com/storybookjs/frontpage/pull/700
<details>
<summary>📦 Published PR as canary version: <code>3.1.1--canary.81.f7bb1cc.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@3.1.1--canary.81.f7bb1cc.0
yarn add @storybook/components-marketing@3.1.1--canary.81.f7bb1cc.0
```
</details>

Remove status page link from Footer

---

src/components/Eyebrow.tsx
src/components/Footer/Services.tsx
src/components/links-context.ts

* Update enterprise link
* Add better utm attributes for various CH links
<details>
<summary>📦 Published PR as canary version: <code>3.1.2--canary.82.013200a.0</code></summary>
<br />
```bash
npm install @storybook/components-marketing@3.1.2--canary.82.013200a.0
yarn add @storybook/components-marketing@3.1.2--canary.82.013200a.0
```
</details>

update enterprise link
